import Nav from '../../components/Nav';
import Footer from '../../components/Footer';

export const metadata = {
  title: 'Terms of Service — SalaryPrep',
  description: 'Terms and conditions for using SalaryPrep salary negotiation playbooks.',
  alternates: { canonical: 'https://www.salaryprep.com/terms' },
};

export default function TermsPage() {
  return (
    <main>
      <Nav />
      <div className="pt-32 pb-20 px-6 max-w-[720px] mx-auto">
        <h1 className="font-serif text-3xl md:text-4xl mb-2">Terms of Service</h1>
        <p className="text-muted text-sm mb-10">Last updated: February 23, 2026</p>

        <div className="prose-custom space-y-8">
          <section>
            <h2 className="font-serif text-xl mb-3 text-ink">1. Acceptance of Terms</h2>
            <p className="text-gray-700 leading-relaxed">
              By accessing or using SalaryPrep (salaryprep.com), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our service. We reserve the right to modify these terms at any time, and your continued use of the service constitutes acceptance of any changes.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl mb-3 text-ink">2. Service Description</h2>
            <p className="text-gray-700 leading-relaxed">
              SalaryPrep provides AI-generated, personalized salary negotiation playbooks. Based on the information you provide (job title, company, salary, experience, and optionally your resume, offer letter, or job listing), we generate a customized PDF document containing negotiation strategies, scripts, market analysis, and recommended actions. The playbook is delivered to your email address.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl mb-3 text-ink">3. Not Professional Advice</h2>
            <p className="text-gray-700 leading-relaxed">
              <strong>SalaryPrep provides informational content only.</strong> Our playbooks are not legal, financial, or professional career advice. The strategies, scripts, and salary data provided are generated by AI based on general market trends and the information you supply. We do not guarantee any specific negotiation outcome. You should use your own judgment when negotiating and consult with appropriate professionals for legal or financial decisions.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl mb-3 text-ink">4. Pricing & Payments</h2>
            <ul className="list-disc list-inside text-gray-700 leading-relaxed space-y-2 ml-2">
              <li>Playbooks are sold as a one-time purchase at the price displayed on the website (currently $39 per playbook).</li>
              <li>Promotional discounts (e.g., code FIRST30 for 30% off) are applied at checkout and may be modified or discontinued at any time.</li>
              <li>All payments are processed securely through Stripe. We do not store your payment card information.</li>
              <li>Prices are in US Dollars (USD) unless otherwise stated.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-serif text-xl mb-3 text-ink">5. Refund Policy</h2>
            <p className="text-gray-700 leading-relaxed">
              We offer a <strong>100% money-back guarantee within 7 days</strong> of purchase, no questions asked. To request a refund, email <a href="mailto:support@salaryprep.com" className="text-accent hover:underline">support@salaryprep.com</a> with your purchase email address. Refunds are processed through Stripe and typically appear within 5-10 business days. You may keep the playbook PDF regardless of whether you request a refund.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl mb-3 text-ink">6. Delivery</h2>
            <p className="text-gray-700 leading-relaxed">
              Your playbook is generated and delivered to the email address you provide, typically within 10 minutes of form submission. If you do not receive your playbook within 30 minutes, please check your spam/junk folder. If it is still missing, contact <a href="mailto:support@salaryprep.com" className="text-accent hover:underline">support@salaryprep.com</a> and we will resend it or provide a direct download.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl mb-3 text-ink">7. Intellectual Property</h2>
            <p className="text-gray-700 leading-relaxed mb-3">
              <strong>Your playbook:</strong> You own the PDF playbook we generate for you. You may use it for your personal negotiations. You may not resell, redistribute, or publish the playbook content commercially.
            </p>
            <p className="text-gray-700 leading-relaxed">
              <strong>Our content:</strong> All website content, blog articles, tools, branding, and design are the intellectual property of SalaryPrep. You may not copy, reproduce, or distribute our content without written permission. The salary negotiation guides on our /companies/ pages are proprietary research content.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl mb-3 text-ink">8. Accuracy of Information</h2>
            <p className="text-gray-700 leading-relaxed">
              Salary data, market ranges, and negotiation strategies in our playbooks and website content are based on publicly available data and AI analysis. While we strive for accuracy, we do not guarantee that any salary figures, market data, or negotiation outcomes are correct or up-to-date. Labor markets change frequently, and individual outcomes vary based on many factors beyond our control.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl mb-3 text-ink">9. User Responsibilities</h2>
            <p className="text-gray-700 leading-relaxed mb-3">By using SalaryPrep, you agree to:</p>
            <ul className="list-disc list-inside text-gray-700 leading-relaxed space-y-2 ml-2">
              <li>Provide accurate information about your career situation to get the most relevant playbook.</li>
              <li>Use the playbook for your personal salary negotiation purposes only.</li>
              <li>Not attempt to abuse, exploit, or reverse-engineer our AI generation system.</li>
              <li>Not use our service for any illegal purpose.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-serif text-xl mb-3 text-ink">10. Limitation of Liability</h2>
            <p className="text-gray-700 leading-relaxed">
              To the fullest extent permitted by law, SalaryPrep shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of our service, including but not limited to loss of income, loss of employment opportunities, or any negotiation outcomes. Our total liability to you for any claim arising from the service shall not exceed the amount you paid for the playbook.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl mb-3 text-ink">11. Free Tools & Content</h2>
            <p className="text-gray-700 leading-relaxed">
              Our free tools (salary quiz, counter-offer calculator) and blog content are provided "as is" for informational purposes. We may modify, update, or remove free tools and content at any time without notice.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl mb-3 text-ink">12. Termination</h2>
            <p className="text-gray-700 leading-relaxed">
              We reserve the right to terminate or suspend access to our service at any time, without notice, for conduct that we believe violates these Terms of Service or is harmful to other users, us, or third parties.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl mb-3 text-ink">13. Governing Law</h2>
            <p className="text-gray-700 leading-relaxed">
              These Terms shall be governed by and construed in accordance with the laws of the United States. Any disputes arising from these terms shall be resolved through good-faith negotiation before pursuing formal legal action.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl mb-3 text-ink">14. Contact</h2>
            <p className="text-gray-700 leading-relaxed">
              For questions about these Terms of Service, please contact us at <a href="mailto:support@salaryprep.com" className="text-accent hover:underline">support@salaryprep.com</a>.
            </p>
          </section>
        </div>
      </div>
      <Footer />
    </main>
  );
}
