import Nav from '../../components/Nav';
import Footer from '../../components/Footer';

export const metadata = {
  title: 'Terms of Service — NegotiateUp',
  description: 'NegotiateUp terms of service. Terms and conditions for using our salary negotiation playbook service.',
  alternates: { canonical: 'https://www.negotiateup.com/terms' },
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-paper">
      <Nav />
      <div className="pt-28 pb-20 px-6">
        <div className="max-w-[680px] mx-auto prose prose-sm">
          <h1 className="font-serif text-3xl mb-8">Terms of Service</h1>
          <p className="text-muted text-sm mb-8">Last updated: February 22, 2026</p>

          <h2 className="font-serif text-xl mt-8 mb-3">1. Service Description</h2>
          <p className="text-muted leading-relaxed mb-4">
            NegotiateUp provides AI-generated, personalized salary negotiation playbooks delivered as PDF documents via email. Each playbook is a one-time purchase tailored to your specific situation based on the information you provide.
          </p>

          <h2 className="font-serif text-xl mt-8 mb-3">2. Payment & Pricing</h2>
          <p className="text-muted leading-relaxed mb-4">
            Playbooks are available for a one-time payment of $39 USD (or the discounted price if a promotion code is applied). All payments are processed securely through Stripe. Prices are subject to change but any changes will not affect orders already placed.
          </p>

          <h2 className="font-serif text-xl mt-8 mb-3">3. Money-Back Guarantee</h2>
          <p className="text-muted leading-relaxed mb-4">
            We offer a 100% money-back guarantee within 7 days of purchase. If you are not satisfied with your playbook for any reason, contact us at support@negotiateup.com and we will issue a full refund. You keep the playbook regardless.
          </p>

          <h2 className="font-serif text-xl mt-8 mb-3">4. Delivery</h2>
          <p className="text-muted leading-relaxed mb-4">
            After payment and form submission, your personalized playbook will be generated and delivered to the email address you provide, typically within 10 minutes. If you do not receive your playbook within 30 minutes, check your spam folder and then contact us for assistance.
          </p>

          <h2 className="font-serif text-xl mt-8 mb-3">5. Disclaimer</h2>
          <p className="text-muted leading-relaxed mb-4">
            NegotiateUp playbooks are informational resources generated by AI based on the data you provide. They are not legal, financial, or employment advice. We do not guarantee specific negotiation outcomes, salary increases, or job offers. Market salary data and company intelligence are estimates and may not reflect current conditions. Always use your own judgment when negotiating.
          </p>

          <h2 className="font-serif text-xl mt-8 mb-3">6. Accuracy</h2>
          <p className="text-muted leading-relaxed mb-4">
            While we strive to provide accurate and useful information, the quality of your playbook depends on the accuracy and completeness of the information you provide. AI-generated content may contain errors or outdated information. Salary ranges, company data, and negotiation strategies are estimates based on available data and should be verified independently.
          </p>

          <h2 className="font-serif text-xl mt-8 mb-3">7. Intellectual Property</h2>
          <p className="text-muted leading-relaxed mb-4">
            Your playbook is generated for your personal use. You may share it with advisors, mentors, or family members for the purpose of your negotiation. You may not resell, redistribute, or publish playbooks. The NegotiateUp brand, website content, and design are our intellectual property.
          </p>

          <h2 className="font-serif text-xl mt-8 mb-3">8. Limitation of Liability</h2>
          <p className="text-muted leading-relaxed mb-4">
            NegotiateUp's total liability for any claim related to our service is limited to the amount you paid for your playbook. We are not liable for any indirect, incidental, or consequential damages arising from the use of our service or playbook content.
          </p>

          <h2 className="font-serif text-xl mt-8 mb-3">9. Changes to Terms</h2>
          <p className="text-muted leading-relaxed mb-4">
            We may update these terms from time to time. Changes will be posted on this page with an updated date. Continued use of our service after changes constitutes acceptance of the updated terms.
          </p>

          <h2 className="font-serif text-xl mt-8 mb-3">10. Contact</h2>
          <p className="text-muted leading-relaxed mb-4">
            For questions about these terms, email <strong>support@negotiateup.com</strong>.
          </p>
        </div>
      </div>
      <Footer />
    </div>
  );
}
