// ============================================
// SalaryPrep — Pre-built Company Index
// Static data for the client-side companies directory
// This file is generated by scripts/build-index.js
// ============================================

// We generate this at build time to avoid fs usage in client code.
// For now, we read from research/ at build time via a script,
// or we can use a server component approach.

// This will be populated by the build script
let _index = null;

export function getCompaniesIndex() {
  if (_index) return _index;

  // Dynamic import only works server-side
  const fs = require('fs');
  const path = require('path');

  const RESEARCH_DIR = path.join(process.cwd(), 'research');
  if (!fs.existsSync(RESEARCH_DIR)) return [];

  const specialNames = {
    'google': 'Google', 'amazon': 'Amazon', 'meta': 'Meta', 'apple': 'Apple',
    'microsoft': 'Microsoft', 'nvidia': 'NVIDIA', 'netflix': 'Netflix',
    'salesforce': 'Salesforce', 'stripe': 'Stripe', 'airbnb': 'Airbnb',
    'uber': 'Uber', 'lyft': 'Lyft', 'spotify': 'Spotify', 'adobe': 'Adobe',
    'coinbase': 'Coinbase', 'snowflake': 'Snowflake', 'databricks': 'Databricks',
    'palantir': 'Palantir', 'shopify': 'Shopify', 'twilio': 'Twilio',
    'crowdstrike': 'CrowdStrike', 'datadog': 'Datadog', 'mongodb': 'MongoDB',
    'hubspot': 'HubSpot', 'pagerduty': 'PagerDuty', 'hashicorp': 'HashiCorp',
    'github': 'GitHub', 'gitlab': 'GitLab', 'atlassian': 'Atlassian',
    'ibm': 'IBM', 'sap': 'SAP', 'asml': 'ASML', 'amd': 'AMD', 'arm': 'Arm',
    'tsmc': 'TSMC', 'jpmorgan': 'JPMorgan', 'goldman-sachs': 'Goldman Sachs',
    'morgan-stanley': 'Morgan Stanley', 'blackrock': 'BlackRock',
    'mckinsey': 'McKinsey', 'bcg': 'BCG', 'bain': 'Bain',
    'deloitte': 'Deloitte', 'pwc': 'PwC', 'ey': 'EY', 'kpmg': 'KPMG',
    'openai': 'OpenAI', 'anthropic': 'Anthropic', 'deepmind': 'DeepMind',
    'bytedance': 'ByteDance', 'tiktok': 'TikTok',
  };

  function formatName(slug) {
    if (specialNames[slug]) return specialNames[slug];
    return slug.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')
      .replace(/\bAi\b/g, 'AI').replace(/\bIo\b/g, 'IO');
  }

  function classifyIndustry(slug) {
    const finance = ['goldman-sachs', 'morgan-stanley', 'jpmorgan', 'blackrock', 'blackstone', 'citadel', 'two-sigma', 'de-shaw', 'jane-street', 'bridgewater', 'bank-of-america', 'citigroup', 'barclays', 'capital-one', 'american-express', 'charles-schwab', 'ally-financial'];
    const consulting = ['mckinsey', 'bcg', 'bain', 'deloitte', 'pwc', 'ey', 'kpmg', 'accenture', 'booz-allen', 'oliver-wyman'];
    const healthcare = ['unitedhealth', 'johnson-johnson', 'pfizer', 'abbvie', 'merck', 'eli-lilly', 'amgen', 'gilead', 'regeneron', 'moderna', 'cerner', 'veeva'];
    if (finance.some(f => slug.includes(f))) return 'Finance';
    if (consulting.some(c => slug.includes(c))) return 'Consulting';
    if (healthcare.some(h => slug.includes(h))) return 'Healthcare';
    return 'Technology';
  }

  const dirs = fs.readdirSync(RESEARCH_DIR, { withFileTypes: true })
    .filter(d => d.isDirectory())
    .map(d => {
      const roles = fs.readdirSync(path.join(RESEARCH_DIR, d.name))
        .filter(f => f.endsWith('.md'));
      return {
        slug: d.name,
        name: formatName(d.name),
        industry: classifyIndustry(d.name),
        roleCount: roles.length,
      };
    })
    .sort((a, b) => a.name.localeCompare(b.name));

  _index = dirs;
  return dirs;
}
