// ============================================
// SalaryPrep — Company Data for Landing Pages
// ============================================

const companies = [
  // ---- BIG TECH ----
  {
    slug: 'google',
    name: 'Google',
    industry: 'Technology',
    logo: '🔍',
    color: '#4285F4',
    tagline: 'Negotiate your Google offer like a pro',
    description: 'Google is known for competitive compensation packages with significant equity (GSUs), generous signing bonuses, and performance bonuses. Their recruiters are skilled negotiators — but there\'s always room to push higher.',
    compStructure: {
      base: '$150K – $350K+',
      equity: 'GSUs vesting over 4 years (often $100K–$500K+)',
      bonus: '15% target annual bonus',
      signing: '$10K – $100K+ (varies by level)',
      other: 'Relocation, 401k match, wellness stipend',
    },
    negotiationTips: [
      'Google almost always has room to increase equity — this is your biggest lever',
      'Signing bonuses are highly negotiable and can bridge the gap in year-one compensation',
      'Competing offers (especially from Meta, Amazon, or startups) significantly increase your leverage',
      'Google uses levels (L3–L10) — make sure your level is correct before negotiating numbers',
      'Target bonus percentage is fixed by level, but base and equity are negotiable',
      'The recruiter\'s first offer is almost never their best — expect 1-2 rounds of negotiation',
    ],
    levels: 'L3 (entry) to L10 (SVP). Most negotiations happen at L4-L7.',
    avgIncrease: '$15,000 – $50,000+',
    keywords: ['Google salary negotiation', 'Google offer negotiation', 'Google compensation', 'Google GSU negotiation'],
  },
  {
    slug: 'amazon',
    name: 'Amazon',
    industry: 'Technology',
    logo: '📦',
    color: '#FF9900',
    tagline: 'Maximize your Amazon total compensation',
    description: 'Amazon has a unique compensation structure with back-loaded RSU vesting (5/15/40/40), signing bonuses to compensate for lower year-one equity, and a base salary cap. Understanding this structure is critical to negotiating well.',
    compStructure: {
      base: '$130K – $185K (hard cap around $185K for most roles)',
      equity: 'RSUs with 5/15/40/40 vesting over 4 years',
      bonus: 'No annual bonus for most roles (equity replaces this)',
      signing: '$20K – $150K+ (split over 2 years, compensates for back-loaded RSUs)',
      other: 'Relocation, 401k match',
    },
    negotiationTips: [
      'Amazon has a base salary cap (~$185K) — don\'t waste negotiation capital here',
      'Focus on RSUs and signing bonus — these are your two biggest levers',
      'The back-loaded vesting schedule (5/15/40/40) means your Year 1-2 cash comp depends heavily on signing bonus',
      'Ask for additional RSU grants to compensate for the vesting cliff',
      'Competing offers are extremely effective — Amazon will often match or beat competitors',
      'Level matters enormously (L4-L7) — push for the higher level if you\'re borderline',
    ],
    levels: 'L4 (entry) to L12 (SVP). Most negotiations happen at L5-L7.',
    avgIncrease: '$20,000 – $80,000+',
    keywords: ['Amazon salary negotiation', 'Amazon offer negotiation', 'Amazon RSU negotiation', 'Amazon compensation'],
  },
  {
    slug: 'meta',
    name: 'Meta',
    industry: 'Technology',
    logo: '♾️',
    color: '#0668E1',
    tagline: 'Get top-of-band at Meta',
    description: 'Meta (Facebook) offers some of the highest total compensation in tech. Their packages include strong base pay, quarterly-vesting RSUs, and significant signing bonuses. Meta is known for being responsive to competing offers.',
    compStructure: {
      base: '$140K – $350K+',
      equity: 'RSUs vesting quarterly over 4 years',
      bonus: '10-20% target annual bonus',
      signing: '$10K – $100K+',
      other: 'Relocation, 401k match, wellness stipend, free meals',
    },
    negotiationTips: [
      'Meta\'s quarterly RSU vesting is a major advantage over Amazon\'s back-loaded schedule — use this in comparison',
      'Meta is very responsive to competing offers, especially from Google and Apple',
      'Push for top-of-band compensation — there\'s meaningful range within each level',
      'Signing bonuses are highly negotiable and often used to close candidates quickly',
      'If you have a competing offer with higher base, Meta will often match on base + add equity',
      'Performance ratings directly affect future RSU refreshers — negotiate your starting equity high',
    ],
    levels: 'E3 (entry) to E9 (VP). Most negotiations happen at E4-E7.',
    avgIncrease: '$15,000 – $60,000+',
    keywords: ['Meta salary negotiation', 'Facebook salary negotiation', 'Meta offer negotiation', 'Meta compensation'],
  },
  {
    slug: 'apple',
    name: 'Apple',
    industry: 'Technology',
    logo: '🍎',
    color: '#000000',
    tagline: 'Negotiate your Apple offer with confidence',
    description: 'Apple offers competitive total compensation with RSUs, signing bonuses, and strong benefits. Apple tends to be more conservative in initial offers compared to other FAANG companies, which means there\'s often significant room to negotiate.',
    compStructure: {
      base: '$140K – $300K+',
      equity: 'RSUs vesting over 4 years (typically equal annual vesting)',
      bonus: '5-20% target annual bonus (varies by org)',
      signing: '$20K – $100K+ (common for senior roles)',
      other: 'ESPP, relocation, education benefits, Apple discounts',
    },
    negotiationTips: [
      'Apple\'s initial offers tend to be below the midpoint — there is almost always room to negotiate',
      'RSU grants and signing bonuses are the most negotiable components',
      'Apple places high value on candidates from other FAANG companies — competing offers are your best leverage',
      'The ESPP (Employee Stock Purchase Plan) at 15% discount is valuable — factor this into your total comp',
      'Hiring managers have significant influence at Apple — if they want you, they\'ll fight for better comp',
      'Apple refresher grants can be generous — but negotiate your initial grant high since refreshers aren\'t guaranteed',
    ],
    levels: 'ICT2 to ICT6+ for engineering. Most negotiations happen at ICT3-ICT5.',
    avgIncrease: '$15,000 – $50,000+',
    keywords: ['Apple salary negotiation', 'Apple offer negotiation', 'Apple compensation negotiation'],
  },
  {
    slug: 'microsoft',
    name: 'Microsoft',
    industry: 'Technology',
    logo: '🪟',
    color: '#00A4EF',
    tagline: 'Level up your Microsoft offer',
    description: 'Microsoft offers well-rounded compensation packages with competitive base salaries, annual bonuses, and stock awards. Their culture of work-life balance and strong benefits make the total package compelling, but the initial offer often leaves room to negotiate.',
    compStructure: {
      base: '$130K – $280K+',
      equity: 'Stock awards vesting over 4 years (equal annual)',
      bonus: '10-30% target annual bonus (by level)',
      signing: '$10K – $75K+ for experienced hires',
      other: '401k match, ESPP, relocation, wellness',
    },
    negotiationTips: [
      'Microsoft levels (59-70+) directly determine your compensation band — confirm your level first',
      'Stock awards are highly negotiable, especially if you have competing offers',
      'Annual bonuses are set by level and performance — focus negotiations on base and equity',
      'Microsoft will match competing offers from Google, Meta, Amazon — always share what you have',
      'Signing bonuses are common for experienced hires and very negotiable',
      'If relocating to a lower cost-of-living area, negotiate before they adjust your offer downward',
    ],
    levels: 'Level 59 (entry) to 70+ (Distinguished Engineer/VP). Most negotiations at 61-67.',
    avgIncrease: '$10,000 – $45,000+',
    keywords: ['Microsoft salary negotiation', 'Microsoft offer negotiation', 'Microsoft compensation'],
  },
  {
    slug: 'netflix',
    name: 'Netflix',
    industry: 'Technology',
    logo: '🎬',
    color: '#E50914',
    tagline: 'Navigate Netflix\'s unique comp model',
    description: 'Netflix has a radically different compensation model — they pay top-of-market base salaries with no annual bonuses. Instead of RSUs, employees can choose to allocate part of their salary to stock options. Understanding this unique structure is key.',
    compStructure: {
      base: '$200K – $600K+ (all-cash, top-of-market)',
      equity: 'Optional — employees can allocate salary to stock options',
      bonus: 'None (baked into higher base salary)',
      signing: 'Not typical (rare exceptions)',
      other: 'Unlimited PTO, no vesting cliffs',
    },
    negotiationTips: [
      'Netflix pays in cash, not equity — your base salary IS your total comp',
      'Research market rate carefully since Netflix aims to pay top-of-market',
      'Netflix re-benchmarks compensation annually — but your starting number sets the baseline',
      'Competing offers with high equity packages can be used to negotiate a higher Netflix base',
      'The stock option allocation is optional — model both scenarios before deciding',
      'Netflix\'s "keeper test" culture means they\'re willing to pay top dollar for top talent',
    ],
    levels: 'Netflix uses fewer formal levels than other tech companies.',
    avgIncrease: '$15,000 – $50,000+',
    keywords: ['Netflix salary negotiation', 'Netflix offer negotiation', 'Netflix compensation'],
  },
  // ---- OTHER TECH ----
  {
    slug: 'salesforce',
    name: 'Salesforce',
    industry: 'Technology',
    logo: '☁️',
    color: '#00A1E0',
    tagline: 'Negotiate smarter at Salesforce',
    description: 'Salesforce offers competitive packages with base salary, RSUs, and performance bonuses. Known for strong culture and benefits, Salesforce compensation can vary significantly by team and role.',
    compStructure: {
      base: '$130K – $280K+',
      equity: 'RSUs vesting over 4 years',
      bonus: '10-20% target annual bonus',
      signing: '$10K – $50K for experienced hires',
      other: 'Wellness reimbursement, volunteer time off, 401k match',
    },
    negotiationTips: [
      'Salesforce RSUs are negotiable — especially if you have competing offers from other tech companies',
      'Signing bonuses are common and highly negotiable for experienced hires',
      'Salesforce matches against other top tech companies — share competing offers',
      'The annual bonus target is level-dependent but actual payout depends on performance',
      'Salesforce has been acquiring companies rapidly — use market data from comparable companies',
      'Remote work policies vary by team — negotiate flexibility upfront if important to you',
    ],
    levels: 'P1-P5 for individual contributors, M1-M5 for managers.',
    avgIncrease: '$10,000 – $40,000+',
    keywords: ['Salesforce salary negotiation', 'Salesforce offer negotiation', 'Salesforce compensation'],
  },
  {
    slug: 'stripe',
    name: 'Stripe',
    industry: 'Technology',
    logo: '💳',
    color: '#635BFF',
    tagline: 'Maximize your Stripe offer',
    description: 'Stripe pays extremely competitively, especially for engineering roles. With strong equity grants and a reputation for hiring top talent, Stripe offers tend to be generous — but there\'s always room to push higher.',
    compStructure: {
      base: '$150K – $320K+',
      equity: 'RSUs or stock options vesting over 4 years',
      bonus: 'Annual performance bonus',
      signing: '$15K – $75K+',
      other: 'Remote work, learning stipend, wellness benefits',
    },
    negotiationTips: [
      'Stripe equity is highly valuable — as a public company, negotiate for more RSUs',
      'Stripe competes directly with FAANG for talent — use competing offers aggressively',
      'Signing bonuses are negotiable and often used to close candidates quickly',
      'Engineering roles tend to have the highest comp — but PM, design, and ops are competitive too',
      'Stripe values mission alignment — showing genuine interest in payments/fintech can help',
      'Ask about RSU refresh policies — Stripe offers competitive annual refreshers for top performers',
    ],
    levels: 'IC1-IC5+ for individual contributors.',
    avgIncrease: '$15,000 – $50,000+',
    keywords: ['Stripe salary negotiation', 'Stripe offer negotiation', 'Stripe compensation'],
  },
  {
    slug: 'uber',
    name: 'Uber',
    industry: 'Technology',
    logo: '🚗',
    color: '#000000',
    tagline: 'Drive your Uber offer higher',
    description: 'Uber offers competitive total compensation with meaningful RSU grants, annual bonuses, and signing bonuses. As a public company, their equity is liquid and vests quarterly.',
    compStructure: {
      base: '$140K – $300K+',
      equity: 'RSUs vesting over 4 years (quarterly)',
      bonus: '10-20% target annual bonus',
      signing: '$10K – $75K+',
      other: 'Uber credits, 401k match, wellness',
    },
    negotiationTips: [
      'Uber RSUs vest quarterly — use this as a selling point when comparing to back-loaded vesting schedules',
      'Competing offers from Lyft, DoorDash, or other tech companies are very effective',
      'Signing bonuses are standard and negotiable for experienced hires',
      'Uber levels (IC1-IC6+) determine your band — make sure you\'re at the right level',
      'Annual RSU refreshers are based on performance — negotiate your initial grant high',
      'If you\'re joining from a competitor, Uber will often provide equity to cover unvested stock',
    ],
    levels: 'IC1-IC6+ for engineering. T4-T8 for technical roles.',
    avgIncrease: '$10,000 – $45,000+',
    keywords: ['Uber salary negotiation', 'Uber offer negotiation', 'Uber compensation'],
  },
  {
    slug: 'airbnb',
    name: 'Airbnb',
    industry: 'Technology',
    logo: '🏠',
    color: '#FF5A5F',
    tagline: 'Unlock more from your Airbnb offer',
    description: 'Airbnb is known for strong compensation packages and a remote-friendly culture. With competitive RSU grants and a focus on hiring the best talent, Airbnb offers often have room for negotiation.',
    compStructure: {
      base: '$150K – $300K+',
      equity: 'RSUs vesting over 4 years',
      bonus: 'Annual performance bonus',
      signing: '$10K – $50K+',
      other: 'Airbnb travel credits, remote flexibility, wellness stipend',
    },
    negotiationTips: [
      'Airbnb\'s live-and-work-anywhere policy is a major perk — factor this into your total comp calculation',
      'RSUs are the primary negotiation lever after base salary',
      'Airbnb competes with FAANG for talent — competing offers carry significant weight',
      'Travel credits ($2K/quarter) add real value — don\'t overlook this in comparisons',
      'Push for a higher level if your experience justifies it — level impacts long-term earnings',
      'Airbnb refresher grants can be generous — but maximize your initial grant',
    ],
    levels: 'IC levels vary by function.',
    avgIncrease: '$10,000 – $40,000+',
    keywords: ['Airbnb salary negotiation', 'Airbnb offer negotiation', 'Airbnb compensation'],
  },
  // ---- FINANCE ----
  {
    slug: 'goldman-sachs',
    name: 'Goldman Sachs',
    industry: 'Finance',
    logo: '🏦',
    color: '#7399C6',
    tagline: 'Negotiate your Goldman Sachs package',
    description: 'Goldman Sachs is one of the highest-paying firms on Wall Street with significant bonus upside. Base salaries follow industry bands, but bonuses — which can equal or exceed base — are where the real money is.',
    compStructure: {
      base: '$110K – $300K+ (by title/level)',
      equity: 'RSUs for VP+ (Restricted Stock Units)',
      bonus: '50-100%+ of base (performance-dependent)',
      signing: '$10K – $100K+ for experienced hires',
      other: 'Health, wellness, 401k, tuition reimbursement',
    },
    negotiationTips: [
      'Base salaries at Goldman are fairly standardized by title — focus on guaranteed bonus and signing bonus',
      'Signing bonuses are very negotiable, especially if you\'re giving up unvested compensation',
      'Guaranteed first-year bonus is common for lateral hires — always ask for one',
      'Title (Analyst, Associate, VP, MD) determines your comp band — push for the right title',
      'Goldman stock RSUs at the VP+ level are a significant part of comp — negotiate the grant size',
      'Competing offers from JPMorgan, Morgan Stanley, or tech companies give you strong leverage',
    ],
    levels: 'Analyst → Associate → VP → MD → Partner',
    avgIncrease: '$15,000 – $75,000+',
    keywords: ['Goldman Sachs salary negotiation', 'Goldman Sachs compensation', 'Goldman Sachs bonus negotiation'],
  },
  {
    slug: 'jpmorgan',
    name: 'JPMorgan Chase',
    industry: 'Finance',
    logo: '🏛️',
    color: '#003A70',
    tagline: 'Maximize your JPMorgan offer',
    description: 'JPMorgan Chase is the largest bank by assets and offers competitive compensation across banking, technology, and operations. Bonus culture is strong, and signing bonuses are common for experienced hires.',
    compStructure: {
      base: '$100K – $275K+',
      equity: 'RSUs for VP+ level',
      bonus: '30-100%+ of base (varies by division)',
      signing: '$10K – $100K+',
      other: 'Health benefits, 401k match, tuition assistance',
    },
    negotiationTips: [
      'JPMorgan base salaries are somewhat standardized — bonuses are where you negotiate',
      'Investment Banking division pays significantly more than Corporate or Technology',
      'Guaranteed first-year bonuses are very common for lateral hires — always negotiate one',
      'Signing bonuses can cover unvested compensation from your current firm (buyout)',
      'Title alignment matters — being slotted at VP vs. Associate makes a huge comp difference',
      'JPMorgan tech roles have become more competitive — use FAANG offers as leverage',
    ],
    levels: 'Analyst → Associate → VP → ED → MD',
    avgIncrease: '$10,000 – $60,000+',
    keywords: ['JPMorgan salary negotiation', 'JPMorgan Chase compensation', 'JPMorgan offer negotiation'],
  },
  {
    slug: 'morgan-stanley',
    name: 'Morgan Stanley',
    industry: 'Finance',
    logo: '📊',
    color: '#002B5C',
    tagline: 'Negotiate your Morgan Stanley package',
    description: 'Morgan Stanley offers strong compensation especially in wealth management and investment banking. Their deferred compensation structure at senior levels makes negotiating upfront comp critical.',
    compStructure: {
      base: '$100K – $275K+',
      equity: 'Deferred comp (stock units) for VP+',
      bonus: '30-100%+ of base',
      signing: '$10K – $80K+',
      other: 'Health, wellness, 401k match',
    },
    negotiationTips: [
      'Morgan Stanley\'s deferred compensation at VP+ levels ties you to the firm — negotiate guaranteed cash upfront',
      'Guaranteed first-year bonus is standard for lateral hires',
      'Signing bonuses can compensate for unvested deferred comp at your current firm',
      'Wealth Management vs. Investment Banking have very different comp structures',
      'Use competing offers from Goldman or JPMorgan to push for a higher package',
      'The base salary may be negotiable at senior levels — don\'t assume it\'s fixed',
    ],
    levels: 'Analyst → Associate → VP → ED → MD',
    avgIncrease: '$10,000 – $50,000+',
    keywords: ['Morgan Stanley salary negotiation', 'Morgan Stanley compensation'],
  },
  // ---- CONSULTING ----
  {
    slug: 'mckinsey',
    name: 'McKinsey & Company',
    industry: 'Consulting',
    logo: '🎯',
    color: '#004B87',
    tagline: 'Negotiate your McKinsey offer',
    description: 'McKinsey offers top-tier consulting compensation with structured pay bands by title. While base salaries are fairly standardized, signing bonuses, relocation packages, and performance bonuses have room for negotiation.',
    compStructure: {
      base: '$110K – $300K+ (by title)',
      equity: 'None (partnership track for senior leaders)',
      bonus: '15-30% performance bonus',
      signing: '$25K – $50K+ (common for MBA hires)',
      other: 'Relocation, wellness, education sponsorship',
    },
    negotiationTips: [
      'McKinsey base salaries are standardized by title — signing bonus is your main lever',
      'MBA signing bonuses are standard ($25K+) but can sometimes be pushed higher',
      'Experienced hires have more negotiation room than campus recruits',
      'If McKinsey is sponsoring your MBA, that adds $200K+ in value — factor this in',
      'Relocation packages are negotiable and can be significant ($10K-$30K)',
      'Performance bonuses at McKinsey are meaningful (up to 30%) and merit-based',
    ],
    levels: 'Business Analyst → Associate → Engagement Manager → Associate Partner → Partner',
    avgIncrease: '$5,000 – $30,000+',
    keywords: ['McKinsey salary negotiation', 'McKinsey compensation', 'McKinsey offer negotiation'],
  },
  {
    slug: 'bain',
    name: 'Bain & Company',
    industry: 'Consulting',
    logo: '🔴',
    color: '#CC0000',
    tagline: 'Get more from your Bain offer',
    description: 'Bain & Company offers competitive consulting compensation with strong culture and benefits. Pay is structured by title with signing bonuses for MBA and experienced hires.',
    compStructure: {
      base: '$105K – $290K+',
      equity: 'None (partnership at senior levels)',
      bonus: '15-25% performance bonus',
      signing: '$25K – $50K+',
      other: 'Relocation, externship program, health benefits',
    },
    negotiationTips: [
      'Bain base pay is standardized — focus on signing bonus and start date flexibility',
      'The externship program (paid time to work elsewhere) is unique to Bain and very valuable',
      'MBA signing bonuses are standard and sometimes negotiable upward',
      'Experienced hires can negotiate title, signing bonus, and start date',
      'Bain\'s profit-sharing at senior levels is a major comp driver',
      'If choosing between MBB firms, use competing offers to push for better signing bonuses',
    ],
    levels: 'Associate Consultant → Consultant → Case Team Leader → Manager → Partner',
    avgIncrease: '$5,000 – $25,000+',
    keywords: ['Bain salary negotiation', 'Bain compensation', 'Bain offer negotiation'],
  },
  {
    slug: 'bcg',
    name: 'Boston Consulting Group (BCG)',
    industry: 'Consulting',
    logo: '🟢',
    color: '#00A651',
    tagline: 'Negotiate your BCG package',
    description: 'BCG rounds out the MBB trio with competitive pay, strong signing bonuses, and excellent benefits. Like McKinsey and Bain, pay is structured by level with negotiation room in bonuses.',
    compStructure: {
      base: '$105K – $290K+',
      equity: 'None (partnership at senior levels)',
      bonus: '15-25% performance bonus',
      signing: '$25K – $50K+',
      other: 'Relocation, sabbatical program, education support',
    },
    negotiationTips: [
      'BCG base salaries are transparent and standardized — signing bonus is your lever',
      'BCG\'s social impact track and sabbatical programs add non-monetary value',
      'MBA signing bonuses are standard and can sometimes be increased',
      'For experienced hires, negotiate your title carefully — it determines your compensation band',
      'BCG office location can affect comp — some offices pay more than others',
      'Competing MBB offers (McKinsey, Bain) are the strongest negotiation leverage',
    ],
    levels: 'Associate → Consultant → Project Leader → Principal → Partner/MD',
    avgIncrease: '$5,000 – $25,000+',
    keywords: ['BCG salary negotiation', 'BCG compensation', 'Boston Consulting Group offer'],
  },
  // ---- MORE TECH ----
  {
    slug: 'nvidia',
    name: 'NVIDIA',
    industry: 'Technology',
    logo: '🎮',
    color: '#76B900',
    tagline: 'Negotiate your NVIDIA offer',
    description: 'NVIDIA has become one of the highest-paying tech companies thanks to its dominance in AI/GPU computing. With stock performance driving massive equity value, NVIDIA offers can be extremely lucrative.',
    compStructure: {
      base: '$140K – $320K+',
      equity: 'RSUs vesting over 4 years (quarterly)',
      bonus: 'No annual bonus for most roles (equity-heavy)',
      signing: '$10K – $50K+',
      other: 'ESPP, 401k match, wellness',
    },
    negotiationTips: [
      'NVIDIA RSUs have been enormously valuable due to stock appreciation — negotiate the grant size aggressively',
      'NVIDIA is fiercely competing for AI/ML talent — use competing offers from Google, Meta, or OpenAI',
      'No annual bonus means equity IS your upside — get the initial grant right',
      'NVIDIA\'s ESPP at a discount is very valuable given the stock trajectory',
      'Hardware engineering and AI research roles command the highest premiums',
      'Stock refreshers at NVIDIA can be generous for top performers, but don\'t rely on them',
    ],
    levels: 'IC levels (ASIC 1-6, SW 1-6).',
    avgIncrease: '$15,000 – $60,000+',
    keywords: ['NVIDIA salary negotiation', 'NVIDIA offer negotiation', 'NVIDIA compensation'],
  },
  {
    slug: 'openai',
    name: 'OpenAI',
    industry: 'Technology',
    logo: '🤖',
    color: '#412991',
    tagline: 'Navigate an OpenAI offer',
    description: 'OpenAI offers premium compensation packages to attract top AI talent. As one of the most sought-after employers in tech, their offers include substantial equity through Profit Participation Units (PPUs) in their unique capped-profit structure.',
    compStructure: {
      base: '$200K – $450K+',
      equity: 'PPUs (Profit Participation Units) with significant upside potential',
      bonus: 'Annual bonus',
      signing: '$25K – $100K+',
      other: 'Health benefits, wellness, meals',
    },
    negotiationTips: [
      'OpenAI PPUs are unique — understand the capped-profit structure and how equity works before negotiating',
      'AI/ML researchers and engineers can command top-of-market compensation',
      'Competing offers from Google DeepMind, Anthropic, or Meta AI are very effective leverage',
      'The brand value of OpenAI on your resume is real — but don\'t accept below-market comp for it',
      'Ask about secondary sale opportunities for PPUs to understand liquidity',
      'OpenAI is growing fast — negotiate your level and scope along with compensation',
    ],
    levels: 'Varies by function, fewer formal levels than FAANG.',
    avgIncrease: '$20,000 – $75,000+',
    keywords: ['OpenAI salary negotiation', 'OpenAI offer negotiation', 'OpenAI compensation'],
  },
  {
    slug: 'tesla',
    name: 'Tesla',
    industry: 'Technology',
    logo: '⚡',
    color: '#CC0000',
    tagline: 'Electrify your Tesla offer',
    description: 'Tesla offers competitive compensation that\'s heavily weighted toward equity. With the stock\'s volatility and potential upside, understanding how to negotiate RSUs at Tesla is critical.',
    compStructure: {
      base: '$120K – $280K+',
      equity: 'RSUs vesting over 4 years',
      bonus: 'Not standard for most roles',
      signing: '$10K – $50K+',
      other: 'ESPP, vehicle discount, 401k match',
    },
    negotiationTips: [
      'Tesla tends to offer lower base salaries than FAANG — push for a higher base since equity is volatile',
      'RSU grants are the primary equity compensation — negotiate aggressively',
      'Competing offers from traditional auto (Rivian, Lucid) or tech companies give you leverage',
      'Tesla\'s mission-driven culture sometimes leads to "passion discount" offers — don\'t accept below market',
      'The employee vehicle discount and ESPP add tangible value to the package',
      'Stock-based refreshers depend on performance — get your initial grant right',
    ],
    levels: 'IC levels vary by engineering discipline.',
    avgIncrease: '$10,000 – $40,000+',
    keywords: ['Tesla salary negotiation', 'Tesla offer negotiation', 'Tesla compensation'],
  },
  // ---- ENTERPRISE / OTHER ----
  {
    slug: 'deloitte',
    name: 'Deloitte',
    industry: 'Consulting',
    logo: '🟩',
    color: '#86BC25',
    tagline: 'Negotiate your Deloitte package',
    description: 'Deloitte is the largest professional services firm and offers competitive compensation across consulting, audit, tax, and advisory. Pay varies significantly by practice area and title.',
    compStructure: {
      base: '$85K – $250K+',
      equity: 'None (partnership at senior levels)',
      bonus: '10-25% based on performance and practice area',
      signing: '$5K – $30K+',
      other: 'Wellness, sabbatical eligibility, education support, 401k match',
    },
    negotiationTips: [
      'Deloitte consulting pays more than audit/tax — make sure you\'re comparing to the right practice area',
      'Signing bonuses are standard for MBA and experienced hires — always negotiate these',
      'Title matters enormously — Consultant vs. Senior Consultant has a meaningful pay difference',
      'Deloitte strategy (Monitor, S&) pays close to MBB levels',
      'Competing offers from other Big 4 or MBB firms are effective leverage',
      'Remote work and office location can affect your base salary — negotiate this early',
    ],
    levels: 'Analyst → Consultant → Senior Consultant → Manager → Senior Manager → Director → Partner/MD',
    avgIncrease: '$5,000 – $20,000+',
    keywords: ['Deloitte salary negotiation', 'Deloitte compensation', 'Deloitte consulting offer'],
  },
  {
    slug: 'oracle',
    name: 'Oracle',
    industry: 'Technology',
    logo: '🔶',
    color: '#F80000',
    tagline: 'Maximize your Oracle offer',
    description: 'Oracle offers competitive compensation for enterprise software roles, especially in cloud infrastructure and database engineering. RSUs, base salary, and signing bonuses make up the typical package.',
    compStructure: {
      base: '$120K – $250K+',
      equity: 'RSUs vesting over 4 years',
      bonus: 'Variable by role and level',
      signing: '$10K – $40K+',
      other: '401k match, ESPP, wellness',
    },
    negotiationTips: [
      'Oracle has been aggressively competing for cloud and AI talent — use this to your advantage',
      'RSUs and signing bonuses are the most negotiable components',
      'Competing offers from AWS, Azure, or Google Cloud carry significant weight',
      'Oracle Cloud Infrastructure (OCI) roles tend to pay more than legacy product roles',
      'Don\'t overlook the ESPP — Oracle\'s stock has performed well recently',
      'Level alignment is important — push for the higher level if you have relevant experience',
    ],
    levels: 'IC1-IC5+ for engineering roles.',
    avgIncrease: '$10,000 – $35,000+',
    keywords: ['Oracle salary negotiation', 'Oracle offer negotiation', 'Oracle compensation'],
  },
  {
    slug: 'adobe',
    name: 'Adobe',
    industry: 'Technology',
    logo: '🎨',
    color: '#FF0000',
    tagline: 'Design a better Adobe offer',
    description: 'Adobe offers competitive total compensation with strong RSU grants, base salary, and annual bonuses. Known for great work-life balance and strong benefits.',
    compStructure: {
      base: '$130K – $260K+',
      equity: 'RSUs vesting over 4 years',
      bonus: '10-20% target annual bonus',
      signing: '$10K – $40K+',
      other: 'Sabbatical program, 401k match, education, wellness',
    },
    negotiationTips: [
      'Adobe RSUs are valuable and negotiable — push for larger grants',
      'The sabbatical program (4 weeks after 5 years) adds meaningful non-monetary value',
      'Competing offers from other creative/enterprise software companies are effective',
      'Annual bonuses are based on company and individual performance — base and equity are your levers',
      'Adobe values product expertise — relevant experience with Adobe products can command a premium',
      'Remote-friendly roles may have location-based pay adjustments — negotiate proactively',
    ],
    levels: 'IC levels (P1-P6+) for individual contributors.',
    avgIncrease: '$10,000 – $35,000+',
    keywords: ['Adobe salary negotiation', 'Adobe offer negotiation', 'Adobe compensation'],
  },
  {
    slug: 'spotify',
    name: 'Spotify',
    industry: 'Technology',
    logo: '🎵',
    color: '#1DB954',
    tagline: 'Tune up your Spotify offer',
    description: 'Spotify offers competitive packages with a unique work-from-anywhere policy. Their compensation includes RSUs, base salary, and bonuses, with a strong emphasis on flexibility and culture.',
    compStructure: {
      base: '$140K – $280K+',
      equity: 'RSUs vesting over 4 years',
      bonus: 'Annual performance bonus',
      signing: '$10K – $40K+',
      other: 'Work from anywhere, wellness, 401k match, Spotify premium',
    },
    negotiationTips: [
      'Spotify\'s Work from Anywhere policy is a major perk — factor this into total comp discussions',
      'RSUs are the main equity component and are negotiable',
      'Competing offers from other streaming/tech companies give you leverage',
      'Spotify adjusts pay by location — if you\'re in a high-cost area, negotiate accordingly',
      'Engineering and data science roles tend to have the highest compensation',
      'Signing bonuses are available and negotiable for experienced hires',
    ],
    levels: 'Individual contributor levels plus management track.',
    avgIncrease: '$10,000 – $35,000+',
    keywords: ['Spotify salary negotiation', 'Spotify offer negotiation', 'Spotify compensation'],
  },
  {
    slug: 'coinbase',
    name: 'Coinbase',
    industry: 'Technology',
    logo: '🪙',
    color: '#0052FF',
    tagline: 'Maximize your Coinbase package',
    description: 'Coinbase offers premium compensation packages, especially for engineering and crypto-native talent. As a remote-first company, they pay competitively regardless of location.',
    compStructure: {
      base: '$150K – $330K+',
      equity: 'RSUs vesting over 4 years',
      bonus: 'Annual performance bonus',
      signing: '$15K – $60K+',
      other: 'Crypto education budget, remote-first, wellness',
    },
    negotiationTips: [
      'Coinbase pays location-agnostic — you get the same comp whether in SF or a low-cost area',
      'RSUs are the biggest negotiation lever — push for a larger equity grant',
      'Competing offers from other fintech or crypto companies (Ripple, Kraken) carry weight',
      'Coinbase stock can be volatile — consider negotiating more guaranteed cash if risk-averse',
      'Signing bonuses are common and negotiable for experienced hires',
      'Crypto/blockchain experience commands a premium — highlight this in negotiations',
    ],
    levels: 'IC levels for individual contributors.',
    avgIncrease: '$15,000 – $50,000+',
    keywords: ['Coinbase salary negotiation', 'Coinbase offer negotiation', 'Coinbase compensation'],
  },
];

export function getAllCompanies() {
  return companies;
}

export function getCompanyBySlug(slug) {
  return companies.find(c => c.slug === slug);
}

export function getCompaniesByIndustry(industry) {
  return companies.filter(c => c.industry === industry);
}

export function getAllSlugs() {
  return companies.map(c => c.slug);
}
